#Console2Design.py
#A class containing the setup for the Console 2's UI
#Distributed under GNU GPL v3
#Nicholas A. Jose
#Feb 2022
#Created by: PyQt5 UI code generator 5.15.6
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1582, 874)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1582, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_console = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_console.sizePolicy().hasHeightForWidth())
        self.dockWidget_console.setSizePolicy(sizePolicy)
        self.dockWidget_console.setMinimumSize(QtCore.QSize(268, 108))
        self.dockWidget_console.setFloating(False)
        self.dockWidget_console.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_console.setObjectName("dockWidget_console")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_12 = QtWidgets.QSplitter(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_12.sizePolicy().hasHeightForWidth())
        self.splitter_12.setSizePolicy(sizePolicy)
        self.splitter_12.setMaximumSize(QtCore.QSize(256, 16777215))
        self.splitter_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.splitter_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.textBrowser_flab_console = QtWidgets.QTextBrowser(self.splitter_5)
        self.textBrowser_flab_console.setEnabled(True)
        self.textBrowser_flab_console.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_flab_console.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_flab_console.setObjectName("textBrowser_flab_console")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label = QtWidgets.QLabel(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(110, 20))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.lineEdit_layout = QtWidgets.QSplitter(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_layout.sizePolicy().hasHeightForWidth())
        self.lineEdit_layout.setSizePolicy(sizePolicy)
        self.lineEdit_layout.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_layout.setMaximumSize(QtCore.QSize(0, 2))
        self.lineEdit_layout.setFrameShape(QtWidgets.QFrame.Box)
        self.lineEdit_layout.setOrientation(QtCore.Qt.Horizontal)
        self.lineEdit_layout.setObjectName("lineEdit_layout")
        self.horizontalLayout.addWidget(self.splitter_12)
        self.dockWidget_console.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_console)
        self.dockWidget_tasks = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_tasks.sizePolicy().hasHeightForWidth())
        self.dockWidget_tasks.setSizePolicy(sizePolicy)
        self.dockWidget_tasks.setMinimumSize(QtCore.QSize(404, 165))
        self.dockWidget_tasks.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_tasks.setObjectName("dockWidget_tasks")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_3.setSizePolicy(sizePolicy)
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_17 = QtWidgets.QSplitter(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_17.sizePolicy().hasHeightForWidth())
        self.splitter_17.setSizePolicy(sizePolicy)
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_17)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_tasks = QtWidgets.QLabel(self.layoutWidget)
        self.label_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_tasks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tasks.setObjectName("label_tasks")
        self.verticalLayout.addWidget(self.label_tasks)
        self.listWidget_tasks = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_tasks.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_tasks.setObjectName("listWidget_tasks")
        self.verticalLayout.addWidget(self.listWidget_tasks)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_start_task = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start_task.setObjectName("pushButton_start_task")
        self.gridLayout_2.addWidget(self.pushButton_start_task, 0, 1, 1, 1)
        self.pushButton_reload_start_task = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reload_start_task.setObjectName("pushButton_reload_start_task")
        self.gridLayout_2.addWidget(self.pushButton_reload_start_task, 1, 1, 1, 1)
        self.pushButton_load_task = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_task.sizePolicy().hasHeightForWidth())
        self.pushButton_load_task.setSizePolicy(sizePolicy)
        self.pushButton_load_task.setObjectName("pushButton_load_task")
        self.gridLayout_2.addWidget(self.pushButton_load_task, 0, 0, 1, 1)
        self.pushButton_stop_task = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop_task.setObjectName("pushButton_stop_task")
        self.gridLayout_2.addWidget(self.pushButton_stop_task, 2, 0, 1, 1)
        self.pushButton_stop_all_tasks = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop_all_tasks.setObjectName("pushButton_stop_all_tasks")
        self.gridLayout_2.addWidget(self.pushButton_stop_all_tasks, 2, 1, 1, 1)
        self.pushButton_reload_task = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reload_task.setObjectName("pushButton_reload_task")
        self.gridLayout_2.addWidget(self.pushButton_reload_task, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.splitter = QtWidgets.QSplitter(self.splitter_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_running_tasks = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_running_tasks.sizePolicy().hasHeightForWidth())
        self.label_running_tasks.setSizePolicy(sizePolicy)
        self.label_running_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_running_tasks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_running_tasks.setObjectName("label_running_tasks")
        self.listWidget_running_tasks = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_running_tasks.sizePolicy().hasHeightForWidth())
        self.listWidget_running_tasks.setSizePolicy(sizePolicy)
        self.listWidget_running_tasks.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_running_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_running_tasks.setObjectName("listWidget_running_tasks")
        self.horizontalLayout_2.addWidget(self.splitter_17)
        self.dockWidget_tasks.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_tasks)
        self.dockWidget_devices = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_devices.sizePolicy().hasHeightForWidth())
        self.dockWidget_devices.setSizePolicy(sizePolicy)
        self.dockWidget_devices.setMinimumSize(QtCore.QSize(252, 119))
        self.dockWidget_devices.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_devices.setObjectName("dockWidget_devices")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_5.setSizePolicy(sizePolicy)
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.dockWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_devices = QtWidgets.QLabel(self.splitter_3)
        self.label_devices.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices.setObjectName("label_devices")
        self.listWidget_devices = QtWidgets.QListWidget(self.splitter_3)
        self.listWidget_devices.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_devices.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_devices.setObjectName("listWidget_devices")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load_device = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_load_device.setObjectName("pushButton_load_device")
        self.gridLayout.addWidget(self.pushButton_load_device, 0, 0, 1, 1)
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_10.sizePolicy().hasHeightForWidth())
        self.splitter_10.setSizePolicy(sizePolicy)
        self.splitter_10.setToolTipDuration(4)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.label_devices_5 = QtWidgets.QLabel(self.splitter_9)
        self.label_devices_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices_5.setObjectName("label_devices_5")
        self.listWidget_device_methods = QtWidgets.QListWidget(self.splitter_9)
        self.listWidget_device_methods.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_device_methods.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_device_methods.setObjectName("listWidget_device_methods")
        self.layoutWidget_5 = QtWidgets.QWidget(self.splitter_9)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_device_test_method = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_device_test_method.setObjectName("pushButton_device_test_method")
        self.gridLayout_8.addWidget(self.pushButton_device_test_method, 0, 0, 1, 1)
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_8.sizePolicy().hasHeightForWidth())
        self.splitter_8.setSizePolicy(sizePolicy)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.label_devices_4 = QtWidgets.QLabel(self.splitter_8)
        self.label_devices_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices_4.setObjectName("label_devices_4")
        self.listWidget_device_attributes = QtWidgets.QListWidget(self.splitter_8)
        self.listWidget_device_attributes.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_device_attributes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_device_attributes.setObjectName("listWidget_device_attributes")
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_8)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_display_device_attribute = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_display_device_attribute.setObjectName("pushButton_display_device_attribute")
        self.gridLayout_7.addWidget(self.pushButton_display_device_attribute, 0, 1, 1, 1)
        self.pushButton_set_device_attribute = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_set_device_attribute.setObjectName("pushButton_set_device_attribute")
        self.gridLayout_7.addWidget(self.pushButton_set_device_attribute, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.splitter_2)
        self.dockWidget_devices.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_devices)
        self.dockWidget_variables = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_variables.sizePolicy().hasHeightForWidth())
        self.dockWidget_variables.setSizePolicy(sizePolicy)
        self.dockWidget_variables.setMinimumSize(QtCore.QSize(195, 140))
        self.dockWidget_variables.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_variables.setObjectName("dockWidget_variables")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_6.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_6.setSizePolicy(sizePolicy)
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dockWidgetContents_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter_7 = QtWidgets.QSplitter(self.dockWidgetContents_6)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_variables = QtWidgets.QLabel(self.splitter_4)
        self.label_variables.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variables.setObjectName("label_variables")
        self.listWidget_variables = QtWidgets.QListWidget(self.splitter_4)
        self.listWidget_variables.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_variables.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_variables.setObjectName("listWidget_variables")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_create_variable = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_create_variable.setObjectName("pushButton_create_variable")
        self.gridLayout_3.addWidget(self.pushButton_create_variable, 0, 0, 1, 1)
        self.pushButton_delete_variable = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_delete_variable.setObjectName("pushButton_delete_variable")
        self.gridLayout_3.addWidget(self.pushButton_delete_variable, 0, 1, 1, 1)
        self.pushButton_set_variable_value = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_set_variable_value.setObjectName("pushButton_set_variable_value")
        self.gridLayout_3.addWidget(self.pushButton_set_variable_value, 1, 0, 1, 2)
        self.splitter_11 = QtWidgets.QSplitter(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_11.sizePolicy().hasHeightForWidth())
        self.splitter_11.setSizePolicy(sizePolicy)
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.label_variables_2 = QtWidgets.QLabel(self.splitter_11)
        self.label_variables_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variables_2.setObjectName("label_variables_2")
        self.listWidget_variable_values = QtWidgets.QListWidget(self.splitter_11)
        self.listWidget_variable_values.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_variable_values.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_variable_values.setObjectName("listWidget_variable_values")
        self.horizontalLayout_5.addWidget(self.splitter_7)
        self.dockWidget_variables.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_variables)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTask_Manager = QtWidgets.QAction(MainWindow)
        self.actionTask_Manager.setObjectName("actionTask_Manager")
        self.actionDevice_Manager = QtWidgets.QAction(MainWindow)
        self.actionDevice_Manager.setObjectName("actionDevice_Manager")
        self.actionVariable_Manager = QtWidgets.QAction(MainWindow)
        self.actionVariable_Manager.setObjectName("actionVariable_Manager")
        self.actionBot_Manager = QtWidgets.QAction(MainWindow)
        self.actionBot_Manager.setObjectName("actionBot_Manager")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLab Console 2.0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.dockWidget_console.setWindowTitle(_translate("MainWindow", "Console"))
        self.label.setText(_translate("MainWindow", "flab command>>"))
        self.dockWidget_tasks.setWindowTitle(_translate("MainWindow", "Task Manager"))
        self.label_tasks.setText(_translate("MainWindow", "Tasks"))
        self.pushButton_start_task.setText(_translate("MainWindow", "Start Task"))
        self.pushButton_reload_start_task.setText(_translate("MainWindow", "Reload/Start Task"))
        self.pushButton_load_task.setText(_translate("MainWindow", "Load Task"))
        self.pushButton_stop_task.setText(_translate("MainWindow", "Stop Task"))
        self.pushButton_stop_all_tasks.setText(_translate("MainWindow", "Stop All Tasks"))
        self.pushButton_reload_task.setText(_translate("MainWindow", "Reload Task"))
        self.label_running_tasks.setText(_translate("MainWindow", "Running Tasks"))
        self.dockWidget_devices.setWindowTitle(_translate("MainWindow", "Device Manager"))
        self.label_devices.setText(_translate("MainWindow", "Devices"))
        self.pushButton_load_device.setText(_translate("MainWindow", "Load Device"))
        self.label_devices_5.setText(_translate("MainWindow", "Device Methods"))
        self.pushButton_device_test_method.setText(_translate("MainWindow", "Test method"))
        self.label_devices_4.setText(_translate("MainWindow", "Device Attributes"))
        self.pushButton_display_device_attribute.setText(_translate("MainWindow", "Display "))
        self.pushButton_set_device_attribute.setText(_translate("MainWindow", "Set"))
        self.dockWidget_variables.setWindowTitle(_translate("MainWindow", "Variable Manager"))
        self.label_variables.setText(_translate("MainWindow", "Variables"))
        self.pushButton_create_variable.setText(_translate("MainWindow", "Create variable"))
        self.pushButton_delete_variable.setText(_translate("MainWindow", "Delete variable"))
        self.pushButton_set_variable_value.setText(_translate("MainWindow", "Set value"))
        self.label_variables_2.setText(_translate("MainWindow", "Variable Value"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionTask_Manager.setText(_translate("MainWindow", "Task Manager"))
        self.actionDevice_Manager.setText(_translate("MainWindow", "Device Manager"))
        self.actionVariable_Manager.setText(_translate("MainWindow", "Variable Manager"))
        self.actionBot_Manager.setText(_translate("MainWindow", "Bot Manager"))
