# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\njose\Dropbox (Cambridge CARES)\Python\flab\flab-personal\Projects\Console3\UIs\Designs\Console3Design_tabbed+plot_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1200, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\njose\\Dropbox (Cambridge CARES)\\Python\\flab\\flab-personal\\Projects\\Console3\\UIs\\Designs\\../../../../../../../../../../Downloads/Flab logo 2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #242424;\n"
"    color: #fff;\n"
"    selection-background-color: #fff;\n"
"    selection-color: #000;\n"
"    border-color: rgb(72, 145, 180);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"        \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: #4a5157;\n"
"    border: 1px solid #003333;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #003333;\n"
"    border-right: 1px solid #003333;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    /*background-color: #003333;*/\n"
"    background-color: #faab2a;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: #de9825;\n"
"    /*background-color: #006666;*/\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: 1px solid #4a5157;\n"
"    padding: 10px;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"    min-width: 200px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"       background-color: #242424;\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    /*background-color: #003333;*/\n"
"    background-color: #faab2a;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 3px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    /*background-color: rgba(70,162,218,50%);*/\n"
"    background-color: #faab2a;\n"
"\n"
"    border: 1px solid #46a2da;\n"
"    color: #000;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #4891b4;\n"
"    color: #fff;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #606060;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #54aad3;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #2385b4;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: #bd5355;\n"
"    border: 1px solid #bd5355;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBox-----*/\n"
"QToolBox\n"
"{\n"
"    background-color: transparent;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: #006d6d;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #4a5157;\n"
"    padding-left: 6px;\n"
"    color: #fff;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"    selection-background-color: #002b2b;\n"
"    selection-color: #fff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: #4a5157;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 4px;\n"
"    width: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDoubleSpinBox & QCalendarWidget-----*/\n"
"QDoubleSpinBox,\n"
"QCalendarWidget QSpinBox \n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button, \n"
"QCalendarWidget QSpinBox::up-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-top-right-radius: 4px;\n"
"    border-width: 1px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:hover, \n"
"QCalendarWidget QSpinBox::up-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:pressed, \n"
"QCalendarWidget QSpinBox::up-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-arrow,\n"
"QCalendarWidget QSpinBox::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button, \n"
"QCalendarWidget QSpinBox::down-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:hover, \n"
"QCalendarWidget QSpinBox::down-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:pressed, \n"
"QCalendarWidget QSpinBox::down-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-arrow,\n"
"QCalendarWidget QSpinBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #1d1d1d;\n"
"    border-radius: 4px;\n"
"    margin-top: 23px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #002b2b;\n"
"    color: #fff;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    padding: 5px;\n"
"    min-width: 100px;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: none;\n"
"    color: #fff;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCalendarWidget-----*/\n"
"QCalendarWidget QToolButton\n"
"{\n"
"      background-color: transparent;\n"
"      color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QToolButton::hover\n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu \n"
"{\n"
"    width: 120px;\n"
"    left: 20px;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QWidget \n"
"{ \n"
"    alternate-background-color: #4a5157; \n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    color: #fff;  \n"
"    background-color: #242424;  \n"
"    selection-background-color: #002b2b; \n"
"    selection-color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"    color: #404040; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    alternate-background-color: transparent;\n"
"    background-color: transparent;\n"
"       border: none;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #002b2b;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    border : none;\n"
"    color: #fff;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"       border: 1px solid #1d1d1d;\n"
"    border-color: rgb(118, 117, 100)\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: transparent;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    /*background-color: rgb(0, 164, 164);*/\n"
"    background-color: #faab2a;\n"
"    border: 1px solid rgb(0, 164, 164);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    /*background-color: rgb(0, 164, 164);*/\n"
"    background-color: #faab2a;\n"
"    border: 1px solid rgb(0, 164, 164);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"\n"
"    /*background-color: rgb(0, 164, 164);*/\n"
"    background-color: #faab2a;\n"
"    border: 1px solid rgb(0, 164, 164);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: lightgray;\n"
"    border: 1px solid #000;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #46a2da; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: #d3d3d3;\n"
"    border: 2px solid #002b2b;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #52beff;\n"
"    border-radius: 6px;\n"
"    background-color: #002b2b;  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:vertical \n"
"{\n"
"   border: none;\n"
"   width: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   width : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal \n"
"{\n"
"   border: none;\n"
"   height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   height : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:horizontal\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:horizontal \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #1d1d1d;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #3b86ae;\n"
"    border-radius: 9px;\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSizeGrip-----*/\n"
"QSizeGrip \n"
"{\n"
"    background-color: image(\"./ressources/sizegrip.png\"); /*To replace*/\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #4a5157;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #9B9B9B;\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    text-align: left; /* align the text to the left */\n"
"    background-color: #4a5157;\n"
"    padding-left: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_console = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_console.sizePolicy().hasHeightForWidth())
        self.dockWidget_console.setSizePolicy(sizePolicy)
        self.dockWidget_console.setMinimumSize(QtCore.QSize(318, 296))
        self.dockWidget_console.setFloating(False)
        self.dockWidget_console.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_console.setObjectName("dockWidget_console")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.splitter_12 = QtWidgets.QSplitter(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_12.sizePolicy().hasHeightForWidth())
        self.splitter_12.setSizePolicy(sizePolicy)
        self.splitter_12.setMaximumSize(QtCore.QSize(256, 16777215))
        self.splitter_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.splitter_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.textBrowser_flab_console = QtWidgets.QTextBrowser(self.splitter_5)
        self.textBrowser_flab_console.setEnabled(True)
        self.textBrowser_flab_console.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_flab_console.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_flab_console.setObjectName("textBrowser_flab_console")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label = QtWidgets.QLabel(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(110, 20))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.lineEdit_layout = QtWidgets.QSplitter(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_layout.sizePolicy().hasHeightForWidth())
        self.lineEdit_layout.setSizePolicy(sizePolicy)
        self.lineEdit_layout.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_layout.setMaximumSize(QtCore.QSize(0, 2))
        self.lineEdit_layout.setFrameShape(QtWidgets.QFrame.Box)
        self.lineEdit_layout.setOrientation(QtCore.Qt.Horizontal)
        self.lineEdit_layout.setObjectName("lineEdit_layout")
        self.horizontalLayout_13.addWidget(self.splitter_12)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_running_tasks_2 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_running_tasks_2.sizePolicy().hasHeightForWidth())
        self.label_running_tasks_2.setSizePolicy(sizePolicy)
        self.label_running_tasks_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_running_tasks_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_running_tasks_2.setObjectName("label_running_tasks_2")
        self.gridLayout_6.addWidget(self.label_running_tasks_2, 0, 0, 1, 1)
        self.graphicsView_tasks_bar = PlotWidget(self.dockWidgetContents)
        self.graphicsView_tasks_bar.setObjectName("graphicsView_tasks_bar")
        self.gridLayout_6.addWidget(self.graphicsView_tasks_bar, 1, 0, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_6)
        self.dockWidget_console.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_console)
        self.dockWidget_managers = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_managers.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_managers.setObjectName("dockWidget_managers")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.task_manager_tab = QtWidgets.QWidget()
        self.task_manager_tab.setObjectName("task_manager_tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.task_manager_tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_tasks = QtWidgets.QLabel(self.task_manager_tab)
        self.label_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_tasks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tasks.setObjectName("label_tasks")
        self.verticalLayout.addWidget(self.label_tasks)
        self.listWidget_tasks = QtWidgets.QListWidget(self.task_manager_tab)
        self.listWidget_tasks.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_tasks.setObjectName("listWidget_tasks")
        self.verticalLayout.addWidget(self.listWidget_tasks)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_load_task = QtWidgets.QPushButton(self.task_manager_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_task.sizePolicy().hasHeightForWidth())
        self.pushButton_load_task.setSizePolicy(sizePolicy)
        self.pushButton_load_task.setObjectName("pushButton_load_task")
        self.gridLayout_2.addWidget(self.pushButton_load_task, 0, 0, 1, 1)
        self.pushButton_start_task = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_start_task.setObjectName("pushButton_start_task")
        self.gridLayout_2.addWidget(self.pushButton_start_task, 0, 1, 1, 1)
        self.pushButton_reload_task = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_reload_task.setObjectName("pushButton_reload_task")
        self.gridLayout_2.addWidget(self.pushButton_reload_task, 1, 0, 1, 1)
        self.pushButton_stop_task = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_stop_task.setObjectName("pushButton_stop_task")
        self.gridLayout_2.addWidget(self.pushButton_stop_task, 1, 1, 1, 1)
        self.pushButton_schedule_task = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_schedule_task.setObjectName("pushButton_schedule_task")
        self.gridLayout_2.addWidget(self.pushButton_schedule_task, 2, 0, 1, 1)
        self.pushButton_stop_all_tasks = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_stop_all_tasks.setObjectName("pushButton_stop_all_tasks")
        self.gridLayout_2.addWidget(self.pushButton_stop_all_tasks, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.task_manager_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_running_tasks = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_running_tasks.sizePolicy().hasHeightForWidth())
        self.label_running_tasks.setSizePolicy(sizePolicy)
        self.label_running_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_running_tasks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_running_tasks.setObjectName("label_running_tasks")
        self.listWidget_running_tasks = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_running_tasks.sizePolicy().hasHeightForWidth())
        self.listWidget_running_tasks.setSizePolicy(sizePolicy)
        self.listWidget_running_tasks.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_running_tasks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_running_tasks.setObjectName("listWidget_running_tasks")
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_kill_task = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_kill_task.setObjectName("pushButton_kill_task")
        self.horizontalLayout_2.addWidget(self.pushButton_kill_task)
        self.pushButton_kill_all_tasks = QtWidgets.QPushButton(self.task_manager_tab)
        self.pushButton_kill_all_tasks.setObjectName("pushButton_kill_all_tasks")
        self.horizontalLayout_2.addWidget(self.pushButton_kill_all_tasks)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.task_manager_tab, "")
        self.Variables = QtWidgets.QWidget()
        self.Variables.setObjectName("Variables")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Variables)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Variables)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_7 = QtWidgets.QSplitter(self.tab)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label_variables = QtWidgets.QLabel(self.splitter_7)
        self.label_variables.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variables.setObjectName("label_variables")
        self.listWidget_variables = QtWidgets.QListWidget(self.splitter_7)
        self.listWidget_variables.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_variables.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_variables.setObjectName("listWidget_variables")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_7)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_create_variable = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_create_variable.setObjectName("pushButton_create_variable")
        self.gridLayout_3.addWidget(self.pushButton_create_variable, 0, 0, 1, 1)
        self.pushButton_delete_variable = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete_variable.setObjectName("pushButton_delete_variable")
        self.gridLayout_3.addWidget(self.pushButton_delete_variable, 0, 1, 1, 1)
        self.pushButton_set_variable_value = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_set_variable_value.setObjectName("pushButton_set_variable_value")
        self.gridLayout_3.addWidget(self.pushButton_set_variable_value, 1, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.splitter_7)
        self.splitter_4 = QtWidgets.QSplitter(self.tab)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_variables_2 = QtWidgets.QLabel(self.splitter_4)
        self.label_variables_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variables_2.setObjectName("label_variables_2")
        self.listWidget_variable_values = QtWidgets.QListWidget(self.splitter_4)
        self.listWidget_variable_values.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_variable_values.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_variable_values.setObjectName("listWidget_variable_values")
        self.horizontalLayout_4.addWidget(self.splitter_4)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter_11 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_11)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_plot_x_variables = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_plot_x_variables.setObjectName("comboBox_plot_x_variables")
        self.gridLayout_5.addWidget(self.comboBox_plot_x_variables, 1, 0, 1, 1)
        self.pushButton_plot_set_x_variable = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_plot_set_x_variable.setObjectName("pushButton_plot_set_x_variable")
        self.gridLayout_5.addWidget(self.pushButton_plot_set_x_variable, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_plot_y_variables = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_plot_y_variables.setObjectName("comboBox_plot_y_variables")
        self.gridLayout_5.addWidget(self.comboBox_plot_y_variables, 3, 0, 1, 1)
        self.pushButton_plot_add_y_variable = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_plot_add_y_variable.setObjectName("pushButton_plot_add_y_variable")
        self.gridLayout_5.addWidget(self.pushButton_plot_add_y_variable, 3, 1, 1, 1)
        self.listWidget_plot_y_variables = QtWidgets.QListWidget(self.splitter_11)
        self.listWidget_plot_y_variables.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_plot_y_variables.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_plot_y_variables.setObjectName("listWidget_plot_y_variables")
        self.pushButton_plot_remove_y_variable = QtWidgets.QPushButton(self.splitter_11)
        self.pushButton_plot_remove_y_variable.setObjectName("pushButton_plot_remove_y_variable")
        self.pushButton_plot_clear_all_y_variables = QtWidgets.QPushButton(self.splitter_11)
        self.pushButton_plot_clear_all_y_variables.setObjectName("pushButton_plot_clear_all_y_variables")
        self.horizontalLayout_5.addWidget(self.splitter_11)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.pushButton_live_plot = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_live_plot.setObjectName("pushButton_live_plot")
        self.verticalLayout_7.addWidget(self.pushButton_live_plot)
        self.graphicsView_plot_2d_plot = PlotWidget(self.tab_2)
        self.graphicsView_plot_2d_plot.setObjectName("graphicsView_plot_2d_plot")
        self.verticalLayout_7.addWidget(self.graphicsView_plot_2d_plot)
        self.label_plot_messages = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plot_messages.sizePolicy().hasHeightForWidth())
        self.label_plot_messages.setSizePolicy(sizePolicy)
        self.label_plot_messages.setObjectName("label_plot_messages")
        self.verticalLayout_7.addWidget(self.label_plot_messages)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.Variables, "")
        self.data_manager_tab = QtWidgets.QWidget()
        self.data_manager_tab.setObjectName("data_manager_tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.data_manager_tab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.data_manager_tab)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter_14 = QtWidgets.QSplitter(self.frame)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.widget = QtWidgets.QWidget(self.splitter_14)
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_data = QtWidgets.QLabel(self.widget)
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.verticalLayout_12.addWidget(self.label_data)
        self.listWidget_data = QtWidgets.QListWidget(self.widget)
        self.listWidget_data.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_data.setObjectName("listWidget_data")
        self.verticalLayout_12.addWidget(self.listWidget_data)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_load_data = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_data.sizePolicy().hasHeightForWidth())
        self.pushButton_load_data.setSizePolicy(sizePolicy)
        self.pushButton_load_data.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_load_data.setObjectName("pushButton_load_data")
        self.horizontalLayout_6.addWidget(self.pushButton_load_data)
        self.pushButton_reload_data = QtWidgets.QPushButton(self.widget)
        self.pushButton_reload_data.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_reload_data.setObjectName("pushButton_reload_data")
        self.horizontalLayout_6.addWidget(self.pushButton_reload_data)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_update_variable = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update_variable.sizePolicy().hasHeightForWidth())
        self.pushButton_update_variable.setSizePolicy(sizePolicy)
        self.pushButton_update_variable.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_update_variable.setObjectName("pushButton_update_variable")
        self.verticalLayout_4.addWidget(self.pushButton_update_variable)
        self.pushButton_update_file = QtWidgets.QPushButton(self.widget)
        self.pushButton_update_file.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_update_file.setObjectName("pushButton_update_file")
        self.verticalLayout_4.addWidget(self.pushButton_update_file)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.widget1 = QtWidgets.QWidget(self.splitter_14)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_data_2 = QtWidgets.QLabel(self.widget1)
        self.label_data_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data_2.setObjectName("label_data_2")
        self.verticalLayout_10.addWidget(self.label_data_2)
        self.listWidget_data_methods = QtWidgets.QListWidget(self.widget1)
        self.listWidget_data_methods.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_data_methods.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_data_methods.setObjectName("listWidget_data_methods")
        self.verticalLayout_10.addWidget(self.listWidget_data_methods)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButton_test_method = QtWidgets.QPushButton(self.widget1)
        self.pushButton_test_method.setObjectName("pushButton_test_method")
        self.gridLayout_15.addWidget(self.pushButton_test_method, 0, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_15)
        self.widget2 = QtWidgets.QWidget(self.splitter_14)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_devices_10 = QtWidgets.QLabel(self.widget2)
        self.label_devices_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices_10.setObjectName("label_devices_10")
        self.verticalLayout_9.addWidget(self.label_devices_10)
        self.listWidget_data_attributes = QtWidgets.QListWidget(self.widget2)
        self.listWidget_data_attributes.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_data_attributes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_data_attributes.setObjectName("listWidget_data_attributes")
        self.verticalLayout_9.addWidget(self.listWidget_data_attributes)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_display_data_attribute = QtWidgets.QPushButton(self.widget2)
        self.pushButton_display_data_attribute.setObjectName("pushButton_display_data_attribute")
        self.gridLayout_13.addWidget(self.pushButton_display_data_attribute, 0, 1, 1, 1)
        self.pushButton_set_data_attribute = QtWidgets.QPushButton(self.widget2)
        self.pushButton_set_data_attribute.setObjectName("pushButton_set_data_attribute")
        self.gridLayout_13.addWidget(self.pushButton_set_data_attribute, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_13)
        self.horizontalLayout_8.addWidget(self.splitter_14)
        self.verticalLayout_6.addWidget(self.frame)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.data_manager_tab, "")
        self.ui_manager_tab = QtWidgets.QWidget()
        self.ui_manager_tab.setObjectName("ui_manager_tab")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.ui_manager_tab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.splitter_18 = QtWidgets.QSplitter(self.ui_manager_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_18.sizePolicy().hasHeightForWidth())
        self.splitter_18.setSizePolicy(sizePolicy)
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_18)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_tasks_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_tasks_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_tasks_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tasks_2.setObjectName("label_tasks_2")
        self.verticalLayout_2.addWidget(self.label_tasks_2)
        self.listWidget_uis = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidget_uis.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_uis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_uis.setObjectName("listWidget_uis")
        self.verticalLayout_2.addWidget(self.listWidget_uis)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_start_ui = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_start_ui.setObjectName("pushButton_start_ui")
        self.gridLayout_4.addWidget(self.pushButton_start_ui, 0, 1, 1, 1)
        self.pushButton_load_ui = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_ui.sizePolicy().hasHeightForWidth())
        self.pushButton_load_ui.setSizePolicy(sizePolicy)
        self.pushButton_load_ui.setObjectName("pushButton_load_ui")
        self.gridLayout_4.addWidget(self.pushButton_load_ui, 0, 0, 1, 1)
        self.pushButton_reload_ui = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_reload_ui.setObjectName("pushButton_reload_ui")
        self.gridLayout_4.addWidget(self.pushButton_reload_ui, 1, 0, 1, 1)
        self.pushButton_stop_ui = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_stop_ui.setObjectName("pushButton_stop_ui")
        self.gridLayout_4.addWidget(self.pushButton_stop_ui, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.splitter_13 = QtWidgets.QSplitter(self.splitter_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_13.sizePolicy().hasHeightForWidth())
        self.splitter_13.setSizePolicy(sizePolicy)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.label_running_uis = QtWidgets.QLabel(self.splitter_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_running_uis.sizePolicy().hasHeightForWidth())
        self.label_running_uis.setSizePolicy(sizePolicy)
        self.label_running_uis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_running_uis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_running_uis.setObjectName("label_running_uis")
        self.listWidget_running_uis = QtWidgets.QListWidget(self.splitter_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_running_uis.sizePolicy().hasHeightForWidth())
        self.listWidget_running_uis.setSizePolicy(sizePolicy)
        self.listWidget_running_uis.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_running_uis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_running_uis.setObjectName("listWidget_running_uis")
        self.horizontalLayout_11.addWidget(self.splitter_18)
        self.tabWidget.addTab(self.ui_manager_tab, "")
        self.device_manager_tab = QtWidgets.QWidget()
        self.device_manager_tab.setObjectName("device_manager_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.device_manager_tab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.splitter_3 = QtWidgets.QSplitter(self.device_manager_tab)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_devices = QtWidgets.QLabel(self.splitter_2)
        self.label_devices.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices.setObjectName("label_devices")
        self.listWidget_devices = QtWidgets.QListWidget(self.splitter_2)
        self.listWidget_devices.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_devices.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_devices.setObjectName("listWidget_devices")
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load_device = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_load_device.setObjectName("pushButton_load_device")
        self.gridLayout.addWidget(self.pushButton_load_device, 0, 0, 1, 1)
        self.pushButton_reload_device = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_reload_device.setObjectName("pushButton_reload_device")
        self.gridLayout.addWidget(self.pushButton_reload_device, 1, 0, 1, 1)
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_10.sizePolicy().hasHeightForWidth())
        self.splitter_10.setSizePolicy(sizePolicy)
        self.splitter_10.setToolTipDuration(4)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.label_devices_5 = QtWidgets.QLabel(self.splitter_9)
        self.label_devices_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices_5.setObjectName("label_devices_5")
        self.listWidget_device_methods = QtWidgets.QListWidget(self.splitter_9)
        self.listWidget_device_methods.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_device_methods.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_device_methods.setObjectName("listWidget_device_methods")
        self.layoutWidget_5 = QtWidgets.QWidget(self.splitter_9)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_device_test_method = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_device_test_method.setObjectName("pushButton_device_test_method")
        self.gridLayout_8.addWidget(self.pushButton_device_test_method, 0, 0, 1, 1)
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_8.sizePolicy().hasHeightForWidth())
        self.splitter_8.setSizePolicy(sizePolicy)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.label_devices_4 = QtWidgets.QLabel(self.splitter_8)
        self.label_devices_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devices_4.setObjectName("label_devices_4")
        self.listWidget_device_attributes = QtWidgets.QListWidget(self.splitter_8)
        self.listWidget_device_attributes.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_device_attributes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_device_attributes.setStyleSheet("")
        self.listWidget_device_attributes.setObjectName("listWidget_device_attributes")
        self.layoutWidget_7 = QtWidgets.QWidget(self.splitter_8)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_display_device_attribute = QtWidgets.QPushButton(self.layoutWidget_7)
        self.pushButton_display_device_attribute.setObjectName("pushButton_display_device_attribute")
        self.gridLayout_7.addWidget(self.pushButton_display_device_attribute, 0, 1, 1, 1)
        self.pushButton_set_device_attribute = QtWidgets.QPushButton(self.layoutWidget_7)
        self.pushButton_set_device_attribute.setObjectName("pushButton_set_device_attribute")
        self.gridLayout_7.addWidget(self.pushButton_set_device_attribute, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.device_manager_tab, "")
        self.model_manager_tab = QtWidgets.QWidget()
        self.model_manager_tab.setObjectName("model_manager_tab")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.model_manager_tab)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_3 = QtWidgets.QFrame(self.model_manager_tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.splitter_15 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.widget3 = QtWidgets.QWidget(self.splitter_15)
        self.widget3.setObjectName("widget3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_model_5 = QtWidgets.QLabel(self.widget3)
        self.label_model_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_model_5.setObjectName("label_model_5")
        self.verticalLayout_17.addWidget(self.label_model_5)
        self.listWidget_models = QtWidgets.QListWidget(self.widget3)
        self.listWidget_models.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_models.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_models.setObjectName("listWidget_models")
        self.verticalLayout_17.addWidget(self.listWidget_models)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.pushButton_evaluate_model = QtWidgets.QPushButton(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_evaluate_model.sizePolicy().hasHeightForWidth())
        self.pushButton_evaluate_model.setSizePolicy(sizePolicy)
        self.pushButton_evaluate_model.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_evaluate_model.setObjectName("pushButton_evaluate_model")
        self.gridLayout_18.addWidget(self.pushButton_evaluate_model, 0, 1, 1, 1)
        self.pushButton_load_model = QtWidgets.QPushButton(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_model.sizePolicy().hasHeightForWidth())
        self.pushButton_load_model.setSizePolicy(sizePolicy)
        self.pushButton_load_model.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_load_model.setObjectName("pushButton_load_model")
        self.gridLayout_18.addWidget(self.pushButton_load_model, 1, 0, 1, 1)
        self.pushButton_train_model = QtWidgets.QPushButton(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_train_model.sizePolicy().hasHeightForWidth())
        self.pushButton_train_model.setSizePolicy(sizePolicy)
        self.pushButton_train_model.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_train_model.setObjectName("pushButton_train_model")
        self.gridLayout_18.addWidget(self.pushButton_train_model, 1, 1, 1, 1)
        self.pushButton_reload_model = QtWidgets.QPushButton(self.widget3)
        self.pushButton_reload_model.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_reload_model.setObjectName("pushButton_reload_model")
        self.gridLayout_18.addWidget(self.pushButton_reload_model, 2, 0, 1, 1)
        self.pushButton_model_predict = QtWidgets.QPushButton(self.widget3)
        self.pushButton_model_predict.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_model_predict.setObjectName("pushButton_model_predict")
        self.gridLayout_18.addWidget(self.pushButton_model_predict, 2, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_18)
        self.widget4 = QtWidgets.QWidget(self.splitter_15)
        self.widget4.setObjectName("widget4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_data_6 = QtWidgets.QLabel(self.widget4)
        self.label_data_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data_6.setObjectName("label_data_6")
        self.verticalLayout_18.addWidget(self.label_data_6)
        self.listWidget_model_methods = QtWidgets.QListWidget(self.widget4)
        self.listWidget_model_methods.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_model_methods.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_model_methods.setObjectName("listWidget_model_methods")
        self.verticalLayout_18.addWidget(self.listWidget_model_methods)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_model_test_method = QtWidgets.QPushButton(self.widget4)
        self.pushButton_model_test_method.setObjectName("pushButton_model_test_method")
        self.gridLayout_19.addWidget(self.pushButton_model_test_method, 0, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_19)
        self.widget5 = QtWidgets.QWidget(self.splitter_15)
        self.widget5.setObjectName("widget5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_models = QtWidgets.QLabel(self.widget5)
        self.label_models.setAlignment(QtCore.Qt.AlignCenter)
        self.label_models.setObjectName("label_models")
        self.verticalLayout_19.addWidget(self.label_models)
        self.listWidget_model_attributes = QtWidgets.QListWidget(self.widget5)
        self.listWidget_model_attributes.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_model_attributes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_model_attributes.setObjectName("listWidget_model_attributes")
        self.verticalLayout_19.addWidget(self.listWidget_model_attributes)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_display_model_attribute = QtWidgets.QPushButton(self.widget5)
        self.pushButton_display_model_attribute.setObjectName("pushButton_display_model_attribute")
        self.gridLayout_20.addWidget(self.pushButton_display_model_attribute, 0, 1, 1, 1)
        self.pushButton_set_model_attribute = QtWidgets.QPushButton(self.widget5)
        self.pushButton_set_model_attribute.setObjectName("pushButton_set_model_attribute")
        self.gridLayout_20.addWidget(self.pushButton_set_model_attribute, 0, 0, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_20)
        self.horizontalLayout_10.addWidget(self.splitter_15)
        self.horizontalLayout_17.addWidget(self.frame_3)
        self.tabWidget.addTab(self.model_manager_tab, "")
        self.horizontalLayout_7.addWidget(self.tabWidget)
        self.dockWidget_managers.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_managers)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.actionRestart_Project = QtWidgets.QAction(MainWindow)
        self.actionRestart_Project.setObjectName("actionRestart_Project")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setChecked(True)
        self.actionConsole.setObjectName("actionConsole")
        self.actionAbout_Console = QtWidgets.QAction(MainWindow)
        self.actionAbout_Console.setObjectName("actionAbout_Console")
        self.actionflab = QtWidgets.QAction(MainWindow)
        self.actionflab.setObjectName("actionflab")
        self.actionConsole_2 = QtWidgets.QAction(MainWindow)
        self.actionConsole_2.setObjectName("actionConsole_2")
        self.actionTroubleshooting = QtWidgets.QAction(MainWindow)
        self.actionTroubleshooting.setObjectName("actionTroubleshooting")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionManagers = QtWidgets.QAction(MainWindow)
        self.actionManagers.setCheckable(True)
        self.actionManagers.setChecked(True)
        self.actionManagers.setObjectName("actionManagers")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addAction(self.actionRestart_Project)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionConsole)
        self.menuView.addAction(self.actionManagers)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flab Console 3.0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.dockWidget_console.setWindowTitle(_translate("MainWindow", "Log"))
        self.label.setText(_translate("MainWindow", "flab command>>"))
        self.label_running_tasks_2.setText(_translate("MainWindow", "Task History"))
        self.dockWidget_managers.setWindowTitle(_translate("MainWindow", "Managers"))
        self.label_tasks.setText(_translate("MainWindow", "Tasks"))
        self.pushButton_load_task.setText(_translate("MainWindow", "Load"))
        self.pushButton_start_task.setText(_translate("MainWindow", "Start"))
        self.pushButton_reload_task.setText(_translate("MainWindow", "Reload"))
        self.pushButton_stop_task.setText(_translate("MainWindow", "Stop"))
        self.pushButton_schedule_task.setText(_translate("MainWindow", "Schedule"))
        self.pushButton_stop_all_tasks.setText(_translate("MainWindow", "Stop All"))
        self.label_running_tasks.setText(_translate("MainWindow", "Running Tasks"))
        self.pushButton_kill_task.setText(_translate("MainWindow", "Kill"))
        self.pushButton_kill_all_tasks.setText(_translate("MainWindow", "Kill All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_manager_tab), _translate("MainWindow", "Tasks"))
        self.label_variables.setText(_translate("MainWindow", "Variables"))
        self.pushButton_create_variable.setText(_translate("MainWindow", "Create variable"))
        self.pushButton_delete_variable.setText(_translate("MainWindow", "Delete variable"))
        self.pushButton_set_variable_value.setText(_translate("MainWindow", "Set value"))
        self.label_variables_2.setText(_translate("MainWindow", "Variable Value"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Values"))
        self.label_3.setText(_translate("MainWindow", "X Variable"))
        self.pushButton_plot_set_x_variable.setText(_translate("MainWindow", "Set X Variable"))
        self.label_2.setText(_translate("MainWindow", "Y Variables"))
        self.pushButton_plot_add_y_variable.setText(_translate("MainWindow", "Add Y Variable"))
        self.pushButton_plot_remove_y_variable.setText(_translate("MainWindow", "Remove Y Variable"))
        self.pushButton_plot_clear_all_y_variables.setText(_translate("MainWindow", "Clear All Y Variables"))
        self.label_4.setText(_translate("MainWindow", "2D Plot"))
        self.pushButton_live_plot.setText(_translate("MainWindow", "Start Live Plot"))
        self.label_plot_messages.setText(_translate("MainWindow", "Messages"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Variables), _translate("MainWindow", "Variables"))
        self.label_data.setText(_translate("MainWindow", "Data"))
        self.pushButton_load_data.setText(_translate("MainWindow", "Load"))
        self.pushButton_reload_data.setText(_translate("MainWindow", "Reload"))
        self.pushButton_update_variable.setText(_translate("MainWindow", "Update Variables"))
        self.pushButton_update_file.setText(_translate("MainWindow", "Update File"))
        self.label_data_2.setText(_translate("MainWindow", "Data Methods"))
        self.pushButton_test_method.setText(_translate("MainWindow", "Test Method"))
        self.label_devices_10.setText(_translate("MainWindow", "Data Attributes"))
        self.pushButton_display_data_attribute.setText(_translate("MainWindow", "Display "))
        self.pushButton_set_data_attribute.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_manager_tab), _translate("MainWindow", "Data"))
        self.label_tasks_2.setText(_translate("MainWindow", "Uis"))
        self.pushButton_start_ui.setText(_translate("MainWindow", "Start"))
        self.pushButton_load_ui.setText(_translate("MainWindow", "Load"))
        self.pushButton_reload_ui.setText(_translate("MainWindow", "Reload"))
        self.pushButton_stop_ui.setText(_translate("MainWindow", "Stop"))
        self.label_running_uis.setText(_translate("MainWindow", "Running Uis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ui_manager_tab), _translate("MainWindow", "User Interfaces"))
        self.label_devices.setText(_translate("MainWindow", "Devices"))
        self.pushButton_load_device.setText(_translate("MainWindow", "Load"))
        self.pushButton_reload_device.setText(_translate("MainWindow", "Reload"))
        self.label_devices_5.setText(_translate("MainWindow", "Device Methods"))
        self.pushButton_device_test_method.setText(_translate("MainWindow", "Test method"))
        self.label_devices_4.setText(_translate("MainWindow", "Device Attributes"))
        self.pushButton_display_device_attribute.setText(_translate("MainWindow", "Display "))
        self.pushButton_set_device_attribute.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.device_manager_tab), _translate("MainWindow", "Devices"))
        self.label_model_5.setText(_translate("MainWindow", "Model"))
        self.pushButton_evaluate_model.setText(_translate("MainWindow", "Evaluate"))
        self.pushButton_load_model.setText(_translate("MainWindow", "Load"))
        self.pushButton_train_model.setText(_translate("MainWindow", "Train"))
        self.pushButton_reload_model.setText(_translate("MainWindow", "Reload"))
        self.pushButton_model_predict.setText(_translate("MainWindow", "Predict"))
        self.label_data_6.setText(_translate("MainWindow", "Model Methods"))
        self.pushButton_model_test_method.setText(_translate("MainWindow", "Test Method"))
        self.label_models.setText(_translate("MainWindow", "Model Attributes"))
        self.pushButton_display_model_attribute.setText(_translate("MainWindow", "Display "))
        self.pushButton_set_model_attribute.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_manager_tab), _translate("MainWindow", "Models"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRestart.setText(_translate("MainWindow", "Restart (Ctrl+R)"))
        self.actionRestart.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionRestart_Project.setText(_translate("MainWindow", "Restart Project (Ctrl+P)"))
        self.actionRestart_Project.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionConsole.setText(_translate("MainWindow", "Log (Ctrl+L)"))
        self.actionConsole.setToolTip(_translate("MainWindow", "Log (Ctrl+L)"))
        self.actionConsole.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionAbout_Console.setText(_translate("MainWindow", "About Console"))
        self.actionflab.setText(_translate("MainWindow", "flab"))
        self.actionConsole_2.setText(_translate("MainWindow", "Console"))
        self.actionTroubleshooting.setText(_translate("MainWindow", "Troubleshooting"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionManagers.setText(_translate("MainWindow", "Managers (Ctrl+M)"))
        self.actionManagers.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
from pyqtgraph import PlotWidget
