# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\njose\Dropbox (Cambridge CARES)\Python\idmt_codeshare\pyflab_CURRENT\Projects/Console3/UIs/Designs/OptionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_optionDialog(QtWidgets.QDialog):
    def setupUi(self, optionDialog):
        optionDialog.setObjectName("optionDialog")
        optionDialog.resize(128, 326)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(optionDialog.sizePolicy().hasHeightForWidth())
        optionDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(optionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(optionDialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(optionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(optionDialog)
        #self.buttonBox.accepted.connect(optionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(optionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(optionDialog)

    def retranslateUi(self, optionDialog):
        _translate = QtCore.QCoreApplication.translate
        optionDialog.setWindowTitle(_translate("optionDialog", "Selection Dialog"))
